AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 20
    DeadLetterQueue:
      Type: SNS
      TargetArn: arn:aws:sns:ap-northeast-1:267428311438:failed-lambda

Resources:
  Main:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.homura.App::handleRequest
      Runtime: java8
      MemorySize: 256
  LogGroupDirectorOfSystem:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Main}
      RetentionInDays: 14

Outputs:
  SlackNotify:
    Description: "Lambda Function ARN"
    Value: !GetAtt Main.Arn
  SlackNotifyIamRole:
    Description: "Implicit IAM Role created for lambda function"
    Value: !GetAtt MainRole.Arn
